<?php

namespace Omnipay\DPO;

use Omnipay\Common\AbstractGateway as BaseAbstractGateway;
use Omnipay\Common\Message\AbstractRequest;

abstract class AbstractGateway extends BaseAbstractGateway
{
    protected function createRequest($class, array $parameters): AbstractRequest
    {
        return parent::createRequest($class, $parameters); // TODO: Change the autogenerated stub
    }
}